### ISSUE TITLE
highest number: players should only be able to enter numbers in empty boxes

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#103]
Lesson: highest number
Sub-lesson: play 3 digit game

Here is an example of being able to replace the value in a box. This should not be possible. Clicking in a box with an existing number should do nothing.
![copy over](https://user-images.githubusercontent.com/39764324/82115470-47038600-97a6-11ea-8f0d-974d2767ad86.gif)

**Comment by yangfcm** [comment]
Fixed.

**Comment by stevenland** [comment]
Thank you Fan :-)
