### ISSUE TITLE
greedy pig: scrollbar obscuring graph

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#63]
Lesson: greedy pig
Sub-lessons: testing theories, comparing strategies

A scrollbar appears at the end of the trials (and another one at the end of "more trials"), partially obscuring the view of the graph. Scrollbars also appear if the screen is resized after running trials.

![scrollbar1](https://user-images.githubusercontent.com/39764324/79546341-9d14d900-80d5-11ea-87d8-065e98f8515a.PNG)
![scrollbar2](https://user-images.githubusercontent.com/39764324/79546347-9f773300-80d5-11ea-8c9a-24cb0e263188.PNG)

**Comment by yangfcm** [comment]
Remove the scroll bar

**Comment by stevenland** [comment]
Great, thank you!
