### ISSUE TITLE
building views: boxes need to be coloured

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#65]
In the lesson building views, the user looks from the side at coloured boxes stacked in front of each other. This should look something like this:

![building views 1](https://user-images.githubusercontent.com/39764324/79550767-24fde180-80dc-11ea-9435-5f91a66e6e5b.PNG)

In the software, the boxes are all grey, making it hard for students to see what is going on.

![building views 2](https://user-images.githubusercontent.com/39764324/79550909-51196280-80dc-11ea-8d77-175a60079f0a.PNG)

**Comment by yangfcm** [comment]
It concerns the design and data structure of the lesson, which means if setting different background color for different number as the old software did, I will have to redesign the lesson. What I can do without breaking the current design is to change the background color to a darker one and make ths size bigger:
 
![Capture](https://user-images.githubusercontent.com/33979421/82297569-fc764980-99f1-11ea-8bef-75bab0f1185e.JPG)

Do you think it is ok?

**Comment by stevenland** [comment]
Your version does look very nice, but honestly I think this will still be confusing for young students. Do you think you would be able to re-design that part of the lesson? If it isn't, we can re-assess the situation.

**Comment by yangfcm** [comment]
It is technically feasible but it requires much work.(The lesson itself is tricky). As color doesn't affect problem-solving, it is only about visual effect, I personally don't think it's worthwhile to redesign the lesson only for a color issue. You said: "I think this will still be confusing for young students.". May I also know what kind of confusion do you mean? If it is a big deal, I can change it.

**Comment by stevenland** [comment]
I'm trying to imagine this problem through the eyes of an 8-year-old child, who is struggling with maths. In the current lesson, the numbers show us where the top of the columns are. But this might not be obvious to a young child. If the squares at the front look the same as the squares further back, it is hard to show depth. If the columns further back differ in colour, it may help the students' brains process what they are seeing.

How big a deal is it? I'm not sure, but I definitely think it would help.

This is just my opinion, and I may be wrong. I'm happy for us to get another opinion, or to close the issue for the moment and work on it if teachers find a problem with it.

**Comment by yangfcm** [comment]
I think what you said makes sense. Let me see if it is possible to fix it.

**Comment by yangfcm** [comment]
Now it's working.

**Comment by stevenland** [comment]
Great! I'll test it when it's pushed to master branch :-)

**Comment by stevenland** [comment]
Oh wait, it's already there. How did I miss that? 

The changes looks absolutely fantastic and I think it will help a lot with visual recognition. Thank you so much for putting all the extra work into this!
