### ISSUE TITLE
cylinder volumes: missing functionality

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#68]
Lesson: cylinder volumes
Sub-lesson: finding the maximum volume

Reproduction steps:
- enter a length and width on the first page
- enter an increment and click "OK"

At this point you will see a list like the following.

![cylinder vol](https://user-images.githubusercontent.com/39764324/79624483-317a4c80-8165-11ea-88bc-29318f795d2b.PNG)

However, we need to add a feature where you can change the current height and click "OK" again to generate new values. Also, the same affect should be achieved by clicking on the rows in the table: 

![cylinder-volumes-feature](https://user-images.githubusercontent.com/39764324/79624528-77371500-8165-11ea-890c-be50c7e26147.gif)

**Comment by yangfcm** [comment]
Missing function is added.

**Comment by stevenland** [comment]
Works well.
