### ISSUE TITLE
addo & multo: selecting a strategy on iOS takes multiple attempts

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#69]
Lessons: Addo & Multo
Sub-lessons: Play a game,   Comparing grids 
(4 sub lessons in total)

On iOS devices (but not in the Chrome devtools emulator), selecting a strategy requires repeated efforts. In the picture below, you can see that the strategy has been selected on the left, but is not showing up in the grids on the right. Clicking on the strategy again leads to it being properly selected. Whilst this is not too much trouble to work around, it could be confusing for students.

![addomulto](https://user-images.githubusercontent.com/39764324/79635223-133b3d80-81b3-11ea-89d2-4171c0a7bbdf.jpg)

Note: the challenge with fixing this is that the behaviour seemingly can't be replicated on a computer.

**Comment by yangfcm** [comment]
Fixed

**Comment by stevenland** [comment]
Works perfectly.
