### ISSUE TITLE
tackling times tables: convert input field into arrow buttons

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#76]
Lesson: tackling times tables
Sub lesson: How many rows?

![ttt1](https://user-images.githubusercontent.com/39764324/79713303-c3728880-8310-11ea-8f7f-8548a562aef3.PNG)

This sub-lesson is designed for very young students, and the idea is fro students to work up to the correct number by clicking the up and down arrows. However, the arrows here are very small, and they should not be able to enter the number directly. My suggestion is to replace the input field with two buttons with arrow icons (from Font Awesome?) and the number next to them.

**Comment by stevenland** [comment]
I think the blue buttons used in "Knight's Tour" would work well for this (ignore the green button).
![buttons up down](https://user-images.githubusercontent.com/39764324/82122349-77631880-97d6-11ea-8405-d84c3eb23c34.PNG)

**Comment by yangfcm** [comment]
Done. add buttons for input

**Comment by stevenland** [comment]
Great!
