### ISSUE TITLE
snakes and ladders: counter starting positions

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#77]
Lesson: snakes and ladders
Sub-lesson: Play a game

When clicking "see who goes first", the counters should:
1. appear off the board (maybe underneath square one)
2. be placed in the order in which they will be starting

In this image, you can see how this is not happening, which may be confusing to the player.

![snakes-and-ladders](https://user-images.githubusercontent.com/39764324/79713841-552ec580-8312-11ea-95f6-774578d92ff0.gif)

**Comment by yangfcm** [comment]
Changed as per requirements

**Comment by stevenland** [comment]
Seems to be working well.
