### ISSUE TITLE
snakes & ladders: add info to table

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#84]
Lesson: snakes & ladders
Sub-lesson: play many games

The table on the right is a bit confusing, because it doesn't show the number of turns for the current game. I would insert a new row ("Turns") to show the number of turns taken in each game simulated.

![image](https://user-images.githubusercontent.com/39764324/79862761-ec327500-8419-11ea-9cd8-63cc4a2936a1.png)

**Comment by yangfcm** [comment]
Info added.

**Comment by stevenland** [comment]
Great!
