### ISSUE TITLE
some lessons need button to take players back to sub-lesson menu

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#87]
In lessons where you make changes to the game rules that are saved, it is reassuring for the player to have a "save and return" button or something similar. Here is a good example of what these lessons should do (from "Win at the fair").

![example1](https://user-images.githubusercontent.com/39764324/79865870-3a964280-841f-11ea-98e9-b52448697cad.gif)

Lessons that need this feature:
- Truth Tiles 2: change the numbers
- Maths of Lotto: choose other games
- Sporting finals (both AFL & NRL): enter teams - OK button is already there, just doesn't return player to menu

**Comment by yangfcm** [comment]
Add the function to these lessons

**Comment by stevenland** [comment]
Great!
