### ISSUE TITLE
fractions should be displayed vertically

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#89]
Lessons:
- Fraction estimation (first 4 sub-lessons)
- What's it worth (find the value of the shape)

Students will find it less confusing and more meaningful if fractions in the software are set up vertically. In several lessons (see above), they are displayed horizontally.

Example of a clear, vertical fraction:
![fractions4](https://user-images.githubusercontent.com/39764324/79994252-0f802180-84f9-11ea-96ee-36d5b65a0652.PNG)

Example of horizontal fractions which could be confusing:
![fractions5](https://user-images.githubusercontent.com/39764324/79994279-14dd6c00-84f9-11ea-9090-5c39d5cf92b8.PNG)

**Comment by yangfcm** [comment]
Display fraction vertically in the two lessons

**Comment by stevenland** [comment]
Looks great. I think we need it for Fraction Estimation: Fraction Number as well. Could we put the input box above the rest of the fraction?

**Comment by yangfcm** [comment]
Yes. Fixed.

**Comment by stevenland** [comment]
Works well. I'll close the issue.
