### ISSUE TITLE
scale graphs based on number of trials

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#90]
Some graphs get stuck with a scale that makes the content very small on the screen. These should be either:
1. scaled at the start of the trials based on the selected number of trials (preferred)
2. Dynamically scale during the simulation.

Lessons affected:
- Highest number (demonstration; play many games fast)
- Have a hexagon (number of times)

- Dice basketball (point distribution)
- First down the mountain (play many games)

An example of a graph with a scale that doesn't make the content fit the window:
![graph-scale](https://user-images.githubusercontent.com/39764324/79994962-f1ff8780-84f9-11ea-93ba-0f98870ef4a1.PNG)

**Comment by yangfcm** [comment]
Scaled graph better in the four lessons.
