### ISSUE TITLE
sporting finals: team entry needs to be fixed and streamlined

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#93]
Lessons: 
1. Sporting Finals (AFL)
2. Sporting Finals (NRL)

Sub-lesson: Enter teams and select final eight

Entering your own teams into the program is problematic:

1. On Safari, it is not possible to type into the fields
2. The "OK" button should take the player back to the lesson sub-menu (back one screen)
3. Team names should remain in the boxes when selecting "Enter teams and select final eight" for a second time
4. Preventing the drop down autocompletion would be nice, but not essential

These issues are discussed here: https://youtu.be/BQGz4W9t79U

**Comment by yangfcm** [comment]
Clicking OK takes user back to menu. 
Disable autocomplete.

**Comment by stevenland** [comment]
waiting for testing feedback on Safari team entry

**Comment by stevenland** [comment]
Are we waiting on any further tests or can we close the issue?

**Comment by yangfcm** [comment]
Any problem with Safari?

**Comment by stevenland** [comment]
No problems on ipad but I thought Mary might want to test on a Mac.

**Comment by yangfcm** [comment]
Okay, no problem.
