### ISSUE TITLE
spirolaterals: resizing window breaks the layout of page

### ISSUE THREAD

**Issue by stevenland** [maths300/lessons#97]
Lesson: spirolaterals
Sub-lesson: draw a spirolateral

When resizing the browser window, the drawing and grid do not scale with the box. Solutions could include scaling them, or stopping the box from scaling.

![spirolaterals](https://user-images.githubusercontent.com/39764324/82021598-73e46a00-96ce-11ea-9a66-f821b0262901.gif)

**Comment by yangfcm** [comment]
The size of canvas can adjust based on the width of window when rendered initially, but as soon as it's rendered, it cannot change with the width of window. I can't see the library supports scaling. Also, in reality, there is no need to resize the window frequently. Even if you do want, just start a new game, then the canvas can be rerendered and its width can be recalculated to fit the window.

**Comment by stevenland** [comment]
I agree, shall we close the issue?
